name: Deploy Remix App to HostIQ

on:
  push:
    branches:
      - main  # Замените на имя вашей основной ветки, если оно отличается

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Укажите необходимую версию Node.js

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Команда для сборки вашего приложения

    - name: Archive production artifacts
      run: tar -czf release.tar.gz ./*  # Архивирует собранные файлы

    # Отправка архива на сервер
    - name: Deploy to HostIQ server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTIQ_HOST }}
        username: ${{ secrets.HOSTIQ_USERNAME }}
        password: ${{ secrets.HOSTIQ_PASSWORD }}
        port: ${{ secrets.HOSTIQ_PORT }}
        source: "release.tar.gz"
        target: "/path/to/your/deployment/directory"

    # Выполнение команд на сервере через SSH для развертывания
    - name: Remote SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTIQ_HOST }}
        username: ${{ secrets.HOSTIQ_USERNAME }}
        password: ${{ secrets.HOSTIQ_PASSWORD }}
        port: ${{ secrets.HOSTIQ_PORT }}
        script: |
          cd /path/to/your/deployment/directory
          tar -xzf release.tar.gz  # Распаковывает архив
          rm release.tar.gz  # Удаление архива после распаковки, если необходимо
          # Команды для запуска вашего приложения
          npm install --production
          pm2 restart all  # или другая команда для запуска приложения
